INSERT INTO products (title, description, image_path)
VALUES 
('Thirst Class Imperial Stocky Oatmeal Stout', 'We’ve taken our house stout - Stocky Oatmeal Stout - and turned up the volume! This edition has all the flavour of the standard beer but with extra body and a fuller flavour. 440ml can, 9.7% ABV', 'uploads/Thirst_Class_Oatmeal_Stout.jpg'),
('Pomona Island Pull Up to the Bumper', 'Imperial Black Forest Gateaux Stout. Driving down those city streets, waiting to get that huge Cherry, Cacao and Vanilla aroma. Won’t you get your big Imperial Stouts, somewhere from Pomona? 440ml can, 11.0% ABV', 'uploads/Pomona_Island_Pull_Up.jpg'),
('Boundary (x Cloudwater) Definitely Not a Thing', 'This Black Triple IPA was brewed in collaboration with Cloudwater as part of their Indie Spotlight series, exclusively for the independent trade. This beer enjoys a 30g/l dry hop smattering of Simcoe, Cascade and Idaho 7. 440ml can, 10.0% ABV', 'uploads/Boundary_Not_a_Thing.jpg'),
('Overtone Broon Sugar', 'A bitter-sweet stout brewed with copious amounts of muscovado sugar for a lingering sweet aftertaste. A rich, decadent beer awaits! 440ml can, 8.0% ABV', 'uploads/Overtone_Broon_Sugar.jpg'),
('Track (x Magnify) Language Barrier', 'Loaded with desiccated coconut & cacao nibs plus processes which boost flavour & mouthfeel that we\'ve been perfecting throughout our journey into stout country. Prepare for full-frontal coconut & chocolate assault, balanced by coffee & cocoa bitterness alongside a smooth boozy warmth. 440ml can, 12.5% ABV', 'uploads/Track_Language_Barrier.jpg'),
('De Moersleutel (x Frontaal) Give or Take', 'This brew contained a triple mash, one of which was a cold steep with all the dark malts to get a super smooth roasty coffee profile. The beer was then dry-hopped with the new experimental hops from Yakima, HBC472, which gives an oaky and earthy notes to the beer. 440ml can, 11.0% ABV', 'uploads/De_Moersleutel_Give_or_Take.jpg'),
('Newbarns (x Sonnen Hill) Nice One', 'Pilsner based around the ideas of Saison brewing. 440ml can, 4.0% ABV', 'uploads/Newbarns_Nice_One.jpg'),
('Cloudwater DDH Pale', 'Our Double Dry Hopped Pale is brewed to soup up your downtime by delivering the hop flavour intensity of our DIPAs at a moderate ABV. Doubling our standard Pale Ale\'s 8g/L dry-hopping rate to 16g/L delivers a bold, juicy, hazy, and intensely aromatic beer. Out of our hoppy beer range, this sets the marker for balance between drinkability and flavour impact. 440ml can, 5.0% ABV', 'uploads/Cloudwater_DDH_Pale.jpg'),
('Squawk Falco', 'A lush orange and parma violet nose with a sweet and hazy clementine body. Light pithy bitterness gives way to a clean boozy warmness. Jam packed with Amarillo, Mosaic and SImcoe Cryo hops. 440ml can, 8.0% ABV', 'uploads/Squawk_Falco.jpg');